### PR TITLE
Make Cython proxy work

### PR DESCRIPTION
**Pull request by psiddire**
Replacing -std=c++11 by -std=c++1y to make the cython proxy work

### CODE REVIEW

**Comment by truggles** [comment]
Hold on you changed these other files beyond your PR comment.  Are you in LFV still using the HZZ code here: https://github.com/uwcms/FinalStateAnalysis/pull/583/files#diff-71b7c8b99083585f4f3950c3acd53b2aL973

Is that why you added it back in?

And this line as well, why did you switch it?  https://github.com/uwcms/FinalStateAnalysis/pull/583/files#diff-71b7c8b99083585f4f3950c3acd53b2aL1187

(Thanks for cleaning up the print 1 2 3 ... in the code)

**Comment by truggles** [comment]
Can I revert this PR and you just change the portions you need updated without overwriting other updates?

**Comment by psiddire** [comment]
Hi Tyler,

Yes, I just realized that. I pushed my make_ntuples_cfg.py by mistake. You
can revert the PR and I will submit only the two files this time.

Regards,

Prasanna,
CERN
385 Route de Meyrin
1217 Meyrin

**Comment by truggles** [comment]
Great.  Thanks for this.

**Pull request merged**
