### PR TITLE
Setup for data taking

### PR DESCRIPTION
**Pull request by dntaylor**
Getting ready for data taking.

Now requires CMSSW_7_4_7. @nwoods lets merge #416 first, then I will rebase.
This still needs a bit of testing. I'll let you know when I think it is ready. The memory leak issue has the nasty hack to increase vsize and memory reqs to 6000. I need to solve that before we merge this in. Otherwise we will only be running on ~600 cores.

### CODE REVIEW

**Comment by lgray** [comment]
I'm guessing you caught that all of the previous EGM branch + new features are now part of the release.
If not please adjust your recipes.

Change log:
https://github.com/cms-sw/cmssw/releases/CMSSW_7_4_7
PR is 10035.

-L

**Comment by lgray** [comment]
Ah, never mind just read your change log. :-)

**Comment by dntaylor** [comment]
Yup :)

**Comment by lgray** [comment]
You may also welcome the addition of "reMiniAOD" which is approximately 10x faster than remaking your own MiniAOD and turns (at least EGM) POG recipes into a cmsDriver command while they are being integrated into the next release.

Runs scheduled or unscheduled. Ask more questions out of PR.

**Comment by nwoods** [comment]
I've already done a merge of #416 and #420 that I'll PR soon after a few
other tweaks. Maybe hold off on this until it's ready to merge, and we can
do it on top of my stuff.

**Comment by nwoods** [comment]
I checked this merged with #422 in 747 and things look ok from the ZZ side.

**Comment by nwoods** [comment]
Superceded by #422, which incorporates these changes. Closing.

**Pull request closed without merging**
