### PR TITLE
Updated PAT locations for 8TeV analyses

### PR DESCRIPTION
**Pull request by nsmith-**
I made a branch for people to push commits referencing #378
When everyone's satisfied the locations are updated, we can merge and delete this branch.
To add commits to this PR, do

```
git checkout -b UpdatedDatadefsFeb15 uwcms/UpdatedDatadefsFeb15
...hack...hack
git commit
git push
```

I made a tool to look for PAT directories in hdfs and match them to `data8TeV.py` datadefs, it might help speed up the process.
You can find it in `MetaData/tuples`
Example usage: `./findUserTuples.py nsmith`
Here is some output for a few users: http://www.hep.wisc.edu/~nsmith/userPAT.html

### CODE REVIEW

**Comment by nsmith-** [comment]
For reference, I find the following MC PAT-tuplizing campaigns in the json:

```
$ cat PATTuples-8TeV.json|sed -n 's:.*/AODSIM/\(.*\)",:\1:p'|sort|uniq
Fall2014_v1
Fall2014_v2
Spring2014PATTuples
Spring2014PATTuples2
Spring2014PATTuples_V2
ZHinv2015
```

The following users have directories listed in the file:

```
belknap
dntaylor
mcepeda
mverzett
nsmith
stephane
```

**Comment by dntaylor** [comment]
@nsmith- Just as a note, generally the pattern is to push changes to your own clone of nsmith-/FinalStateAnalysis and then issue a PR to the target uwcms branch rather than create a development branch in uwcms/FinalStateAnalysis.

**Comment by nsmith-** [comment]
@dntaylor, I think that for this particular situation, that is not an ideal approach for a pull request, since it requires team input.  Because individual user repositories are only writable by that user, the team cannot all add their commits to a particular topic branch in a unified manner, generating multiple pull requests for a single topic rather than one.  For this particular issue, I think it seems better to use the [shared repository model](https://help.github.com/articles/using-pull-requests/#shared-repository-model)
Pull requests from individual forks are generally for the case when the individual is less intimately connected to the base repository, and has no write permissions to the base repository.  It is commonly used for external contributors to help develop open source software projects, but for internal contributors, the alternative method is to push a topic branch to the shared repository and then after (possibly multiple) other team members have verified the changeset, it is merged to master.  This is not always better but for some situations it is.  One of the golden rules of git is never push to master. (and of course there are exceptions to that)

**Comment by mcepeda** [comment]
Hi Nick,
I see your point, but I am not sure it applies to this case, I might be misunderstanding.... For instance, issue #378 that you are referencing dates Nov2014.
Are you saying that from Nov2014 until now, Feb2015, we should have all been collecting the PRs in one branch until everything is perfect and then push that one?
I imagine I got this wrong?

With everybody working on a particular issue, finding different bugs, just commiting things to branches before merging will prove ineffective. I agree that if a core of 2-3 people are working on a particular task, then we do need to do a special branch and wait to merge that one (this is the same thing we did when we created a 53X_Dev branch, separating it from the older setup), but that is not the usual scenario.

On the other hand: I do like (very much) your point about how in the future we really need to get better at bookeeping. Until now all the efforts to bookeep the patuples were in vain.  Your tool will prove very useful. But with miniAOD not being necessary to have in UW, I imagine that MetaData as a concept might be a little bit redundant? We will be running over data that wont be in UW, but over in different T2s. So we might need to broaden it a bit.

Best,

Maria

**Comment by nsmith-** [comment]
Lets keep the branch around, some useful tools there.

**Comment by dntaylor** [comment]
Here are all the ones I use if you want to update and merge:

```
{
    "data_DoubleMu_Run2012A_22Jan2013_v1" : "/hdfs/store/user/belknap/DoubleMu/Run2012A-22Jan2013-v1/AOD/Spring2014PATTuples_V2",
    "data_DoubleMuParked_Run2012B_22Jan2013_v1" : "/hdfs/store/user/belknap/DoubleMuParked/Run2012B-22Jan2013-v1/AOD/Spring2014PATTuples_V2",
    "data_DoubleMuParked_Run2012C_22Jan2013_v1" : "/hdfs/store/user/belknap/DoubleMuParked/Run2012C-22Jan2013-v1/AOD/Spring2014PATTuples_V2",
    "data_DoubleMuParked_Run2012D_22Jan2013_v1" : "/hdfs/store/user/belknap/DoubleMuParked/Run2012D-22Jan2013-v1/AOD/Spring2014PATTuples_V2",

    "data_DoubleElectron_Run2012A_22Jan2013_v1" : "/hdfs/store/user/belknap/DoubleElectron/Run2012A-22Jan2013-v1/AOD/Spring2014PATTuples_V2",
    "data_DoubleElectron_Run2012B_22Jan2013_v1" : "/hdfs/store/user/belknap/DoubleElectron/Run2012B-22Jan2013-v1/AOD/Spring2014PATTuples_V2",
    "data_DoubleElectron_Run2012C_22Jan2013_v1" : "/hdfs/store/user/belknap/DoubleElectron/Run2012C-22Jan2013-v1/AOD/Spring2014PATTuples_V2",
    "data_DoubleElectron_Run2012D_22Jan2013_v1" : "/hdfs/store/user/belknap/DoubleElectron/Run2012D-22Jan2013-v1/AOD/Spring2014PATTuples_V2",

    "data_MuEG_Run2012A_22Jan2013_v1" : "/hdfs/store/user/belknap/MuEG/Run2012A-22Jan2013-v1/AOD/Spring2014PATTuples_V2",
    "data_MuEG_Run2012B_22Jan2013_v1" : "/hdfs/store/user/belknap/MuEG/Run2012B-22Jan2013-v1/AOD/Spring2014PATTuples_V2",
    "data_MuEG_Run2012C_22Jan2013_v1" : "/hdfs/store/user/belknap/MuEG/Run2012C-22Jan2013-v1/AOD/Spring2014PATTuples_V2",
    "data_MuEG_Run2012D_22Jan2013_v1" : "/hdfs/store/user/belknap/MuEG/Run2012D-22Jan2013-v1/AOD/Spring2014PATTuples_V2",

    "data_SingleMu_Run2012A_22Jan2013_v1" : "/hdfs/store/user/tperry/SingleMu/Run2012A-22Jan2013-v1/AOD/Spring2014PATTuples_v3",
    "data_SingleMu_Run2012B_22Jan2013_v1" : "/hdfs/store/user/tperry/SingleMu/Run2012B-22Jan2013-v1/AOD/Spring2014PATTuples_v3",
    "data_SingleMu_Run2012C_22Jan2013_v1" : "/hdfs/store/user/tperry/SingleMu/Run2012C-22Jan2013-v1/AOD/Spring2014PATTuples_v3",
    "data_SingleMu_Run2012D_22Jan2013_v1" : "/hdfs/store/user/tperry/SingleMu/Run2012D-22Jan2013-v1/AOD/Spring2014PATTuples_v3",

    "data_SingleElectron_Run2012A_22Jan2013_v1" : "/hdfs/store/user/tperry/DataA_8TeVEle-skimpattuple_cfg",
    "data_SingleElectron_Run2012B_22Jan2013_v1" : "/hdfs/store/user/tperry/DataB_8TeVEle-skimpattuple_cfg",
    "data_SingleElectron_Run2012C_22Jan2013_v1" : "/hdfs/store/user/tperry/DataC_8TeVEle-skimpattuple_cfg",
    "data_SingleElectron_Run2012D_22Jan2013_v1" : "/hdfs/store/user/tperry/DataD_8TeVEle-skimpattuple_cfg",

    "HPlusPlusHMinusMinusHTo4L_M-110_8TeV-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusMinusHTo4L_M-110_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusMinusHTo4L_M-130_8TeV-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusMinusHTo4L_M-130_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusMinusHTo4L_M-150_8TeV-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusMinusHTo4L_M-150_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusMinusHTo4L_M-170_8TeV-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusMinusHTo4L_M-170_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusMinusHTo4L_M-200_8TeV-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusMinusHTo4L_M-200_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusMinusHTo4L_M-250_8TeV-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusMinusHTo4L_M-250_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusMinusHTo4L_M-300_8TeV-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusMinusHTo4L_M-300_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusMinusHTo4L_M-350_8TeV-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusMinusHTo4L_M-350_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusMinusHTo4L_M-400_8TeV-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusMinusHTo4L_M-400_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusMinusHTo4L_M-450_8TeV-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusMinusHTo4L_M-450_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusMinusHTo4L_M-500_8TeV-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusMinusHTo4L_M-500_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusMinusHTo4L_M-600_8TeV-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusMinusHTo4L_M-600_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusMinusHTo4L_M-700_8TeV-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusMinusHTo4L_M-700_8TeV-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",

    "HPlusPlusHMinusHTo3L_M-170_8TeV-calchep-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusHTo3L_M-170_8TeV-calchep-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusHTo3L_M-200_8TeV-calchep-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusHTo3L_M-200_8TeV-calchep-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusHTo3L_M-250_8TeV-calchep-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusHTo3L_M-250_8TeV-calchep-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusHTo3L_M-300_8TeV-calchep-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusHTo3L_M-300_8TeV-calchep-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusHTo3L_M-350_8TeV-calchep-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusHTo3L_M-350_8TeV-calchep-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusHTo3L_M-400_8TeV-calchep-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusHTo3L_M-400_8TeV-calchep-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusHTo3L_M-450_8TeV-calchep-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusHTo3L_M-450_8TeV-calchep-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusHTo3L_M-500_8TeV-calchep-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusHTo3L_M-500_8TeV-calchep-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusHTo3L_M-600_8TeV-calchep-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusHTo3L_M-600_8TeV-calchep-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "HPlusPlusHMinusHTo3L_M-700_8TeV-calchep-pythia6" : "/hdfs/store/user/dntaylor/HPlusPlusHMinusHTo3L_M-700_8TeV-calchep-pythia6/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",

    "WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball-v1" : "/store/user/tperry/WJets_p1_s-skimpattuple_cfg",
    "WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball-v2" : "/store/user/tperry/WJets_p2_s-skimpattuple_cfg",

    "W1JetsToLNu_TuneZ2Star_8TeV-madgraph" : "/store/user/tperry/W1Jet_p1_s-skimpattuple_cfg",
    "W2JetsToLNu_TuneZ2Star_8TeV-madgraph" : "/store/user/tperry/W2Jet_p1_s-skimpattuple_cfg",
    "W3JetsToLNu_TuneZ2Star_8TeV-madgraph" : "/store/user/tperry/W3Jet_p1_s-skimpattuple_cfg",
    "W4JetsToLNu_TuneZ2Star_8TeV-madgraph" : "/store/user/tperry/W4Jet_p1_s-skimpattuple_cfg",
    "WbbJetsToLNu_Massive_TuneZ2star_8TeV-madgraph-pythia6_tauola" : "/store/user/tperry/WbbJetsToLNu_Massive_TuneZ2star_8TeV-madgraph-pythia6_tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",

    "Z1jets_M50" : "/hdfs/store/user/dntaylor/DY1JetsToLL_M-50_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "Z2jets_M50_S10" : "/hdfs/store/user/dntaylor/DY2JetsToLL_M-50_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",
    "Z3jets_M50" : "/hdfs/store/user/dntaylor/DY3JetsToLL_M-50_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "Z4jets_M50" : "/hdfs/store/user/dntaylor/DY4JetsToLL_M-50_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",

    "DYJetsToLL_M-50_TuneZ2Star_8TeV-madgraph-tarball" : "/hdfs/store/user/dntaylor/DYJetsToLL_M-50_TuneZ2Star_8TeV-madgraph-tarball/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "DYJetsToLL_M-10To50filter_8TeV-madgraph" : "/hdfs/store/user/nsmith/DYJetsToLL_M-10To50filter_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/ZHinv2015",

    "T_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola" : "/hdfs/store/user/mcepeda/T_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "Tbar_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola" : "/hdfs/store/user/mcepeda/Tbar_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "T_t-channel_TuneZ2star_8TeV-powheg-tauola" : "/hdfs/store/user/tperry/TToLeptons_t-channel_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "Tbar_t-channel_TuneZ2star_8TeV-powheg-tauola" : "/hdfs/store/user/tperry/TBarToLeptons_t-channel_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "T_s-channel_TuneZ2star_8TeV-powheg-tauola" : "/hdfs/store/user/tperry/T_s-channel_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "Tbar_s-channel_TuneZ2star_8TeV-powheg-tauola" : "/hdfs/store/user/tperry/Tbar_s-channel_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",

    "TTJetsFullLepMGDecays" : "/hdfs/store/user/mcepeda/TTJets_FullLeptMGDecays_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7C-v2/AODSIM/Fall2014PATTuples_V1",
    "TTJetsSemiLepMGDecays" : "/hdfs/store/user/mcepeda/TTJets_SemiLeptMGDecays_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/Fall2014PATTuples_V1",

    "WWJetsTo2L2Nu_TuneZ2star_8TeV-madgraph-tauola" : "/hdfs/store/user/aglevine/WWJetsTo2L2Nu_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",

    "WZJetsTo2L2Q_TuneZ2star_8TeV-madgraph-tauola" : "/hdfs/store/user/aglevine/WZJetsTo2L2Q_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",
    "WZJetsTo3LNu_TuneZ2_8TeV-madgraph-tauola" : "/hdfs/store/user/aglevine/WZJetsTo3LNu_TuneZ2_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",

    "WGstarToLNu2E_TuneZ2star_8TeV-madgraph-tauola" : "/hdfs/store/user/dntaylor/WGstarToLNu2E_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "WGstarToLNu2Mu_TuneZ2star_8TeV-madgraph-tauola" : "/hdfs/store/user/dntaylor/WGstarToLNu2Mu_TuneZ2star_7TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",

    "ZZTo4e_8TeV-powheg-pythia6" : "/hdfs/store/user/aglevine/ZZTo4e_8TeV-powheg-pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",
    "ZZTo4mu_8TeV-powheg-pythia6" : "/hdfs/store/user/aglevine/ZZTo4mu_8TeV-powheg-pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",
    "ZZTo4tau_8TeV-powheg-pythia6" : "/hdfs/store/user/aglevine/ZZTo4tau_8TeV-powheg-pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",
    "ZZTo2e2mu_8TeV-powheg-pythia6" : "/hdfs/store/user/aglevine/ZZTo2e2mu_8TeV-powheg-pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",
    "ZZTo2e2tau_8TeV-powheg-pythia6" : "/hdfs/store/user/aglevine/ZZTo2e2tau_8TeV-powheg-pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",
    "ZZTo2mu2tau_8TeV-powheg-pythia6" : "/hdfs/store/user/aglevine/ZZTo2mu2tau_8TeV-powheg-pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",

    "ZZJetsTo2L2Q_TuneZ2star_8TeV-madgraph-tauola" : "/hdfs/store/user/aglevine/ZZJetsTo2L2Q_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",
    "ZZJetsTo2L2Nu_TuneZ2star_8TeV-madgraph-tauola" : "/hdfs/store/user/dntaylor/ZZJetsTo2L2Nu_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v3/AODSIM/Fall2014PATTuples_V1",
    "ZZJetsTo4L_TuneZ2star_8TeV-madgraph-tauola" : "/hdfs/store/user/aglevine/ZZJetsTo4L_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",

    "GluGluToZZTo4L_8TeV-gg2zz-pythia6" : "/hdfs/store/user/belknap/GluGluToZZTo4L_8TeV-gg2zz-pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Spring2014PATTuples_V2",
    "GluGluToZZTo2L2L_TuneZ2star_8TeV-gg2zz-pythia6" : "/hdfs/store/user/belknap/GluGluToZZTo2L2L_TuneZ2star_8TeV-gg2zz-pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Spring2014PATTuples_V2",

    "GluGluToHToZZTo4L_M-125_8TeV-powheg-pythia6" : "/hdfs/store/user/dntaylor/GluGluToHToZZTo4L_M-125_8TeV-powheg-pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",

    "ZGToLLG_8TeV-madgraph" : "/hdfs/store/user/dntaylor/ZGToLLG_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",

    "WW_TuneZ2star_8TeV_pythia6_tauola" : "/hdfs/store/user/aglevine/WW_TuneZ2star_8TeV_pythia6_tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",
    "WZ_TuneZ2star_8TeV_pythia6_tauola" : "/hdfs/store/user/aglevine/WZ_TuneZ2star_8TeV_pythia6_tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",
    "ZZ_TuneZ2star_8TeV_pythia6_tauola" : "/hdfs/store/user/aglevine/ZZ_TuneZ2star_8TeV_pythia6_tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATuples_V1",

    "TTGJets" : "/hdfs/store/user/dntaylor/TTGJets_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM/Fall2014PATTuples_V1",
    "TTWJets" : "/hdfs/store/user/dntaylor/TTWJets_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "TTWWJets" : "/hdfs/store/user/dntaylor/TTWWJets_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "TTZJets" : "/hdfs/store/user/dntaylor/TTZJets_8TeV-madgraph_v2/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "WWGJets" : "/hdfs/store/user/dntaylor/WWGJets_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "WWWJets" : "/hdfs/store/user/dntaylor/WWWJets_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "WWZNoGstarJets" : "/hdfs/store/user/dntaylor/WWZNoGstarJets_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "WZZNoGstarJets" : "/hdfs/store/user/dntaylor/WZZNoGstarJets_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1",
    "ZZZNoGstarJets" : "/hdfs/store/user/dntaylor/ZZZNoGstarJets_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/Fall2014PATTuples_V1"
}

```

**Pull request closed without merging**
