### PR TITLE
Update to CMSSW_7_4_14, add ZZ analysis Z+l control region, bunch of small modifications

### PR DESCRIPTION
**Pull request by nwoods**
Small modifications include:
- `resubmit_failed_jobs.py` can resubmit individual samples (still supports resubmitting all samples in job as before).
- Fix bug in `submit_job.py` that prevented the `--bunch-spacing` option from working (and printed an extremely confusing error message).
- Standard EGamma IDs are now included by default, no merging needed in setup recipe.
- Update to latest version of Virtualenv (master branch). 
- Data global tag updated to correct version for the 23 September rereco.
  - Global tags are no longer set as Unix environment variables (or printed by `environment.sh`) because these weren't used anywhere and were just confusing.

### CODE REVIEW

**Comment by nwoods** [comment]
Oops, I was wrong about the egamma IDs being included by default, so I put them back in. I was confused by the fact that the non-triggering MVA IDs are in by default, but the triggering MVA IDs are not.

**Comment by nwoods** [comment]
@dntaylor, is Jenkins down again?

**Comment by dntaylor** [comment]
Yeah, its full, I look at it tomorrow

**Comment by dntaylor** [comment]
test this please

**Comment by aglevine** [comment]
Nate, could you also update the README to specify that CMSSW_7_4_14 is now used instead of CMSSW_7_4_7? The outdated instructions on the README are confusing some newer people from LFV land who are trying to get FSA setup. We were on CMSSW_7_4_12 before this newest PR, right?

**Comment by lgray** [comment]
Should have been 7_4_12_patch2 or _patch4.

**Comment by aglevine** [comment]
Just noticed that Nate had in fact updated the README in this PR. So disregard most of my previous comment :)

**Comment by dntaylor** [comment]
@nwoods please cherry pick this commit: bf775486cef8265f803f960433e3a228ec3480f9

**Comment by dntaylor** [comment]
@nwoods and e60bcf30dcc709a8dbc6163d5398b977098c0441 is the v2

**Comment by nwoods** [comment]
@dntaylor: done.

@aglevine: ;)

**Pull request merged**
