### PR TITLE
Test Jenkins with horribly broken PR

### PR DESCRIPTION
**Pull request by nwoods**

### CODE REVIEW

**Comment by nwoods** [comment]
Well, that's no good.

**Comment by nwoods** [comment]
Wait, why did leaving that comment make Jenkins start testing it again? Now I'm leaving another comment to see what happens.

**Comment by nwoods** [comment]
... putting up another commit to see if the problem is fixed.

**Comment by nwoods** [comment]
For some reason it's checking out the HEAD of the branch instead of the last commit in this PR. @dntaylor is investigating.

**Comment by dntaylor** [comment]
test this please

**Comment by dntaylor** [comment]
test this please

**Comment by dntaylor** [comment]
test this please

**Comment by dntaylor** [comment]
test this please

**Comment by nwoods** [comment]
... and another test

**Comment by nwoods** [comment]
Victory! Jenkins tried to compile this garbage, failed because it's garbage, and told us that it failed. Next we'll implement some physics tests, but this represents a solid start.

**Pull request closed without merging**
