### PR TITLE
HZZ Categories

### PR DESCRIPTION
**Pull request by nwoods**
A plugin to find the H->4l category for each event and embed it in the PATFinalState. I'm including it here mostly so that this branch matches the 74X branch that I'm about to merge this into.

Some code to do my alternative version of FSR recovery may appear before this is merged. If not, I'll just PR it separately.

### CODE REVIEW

**Comment by nwoods** [comment]
I just discovered that a weird bug I found, where some events had rows missing from the ntuple, was caused by [this line](https://github.com/uwcms/FinalStateAnalysis/blob/miniAOD_dev/NtupleTools/python/ntuple_builder.py#L377), which limits events inexplicably to 50 rows. I just pushed another commit to this PR to change that to 999. It's only very rarely a problem, but I bet this has messed with people a bit in the past without anyone realizing it. 

If somebody could check this whole PR out and merge it soon, I'd really appreciate it.

**Comment by dntaylor** [comment]
Is this ready to merge?

**Comment by nwoods** [comment]
It is as far as I know, but you might do a quick check of your stuff to
make sure.

**Comment by dntaylor** [comment]
Already did. Merging

**Comment by dntaylor** [comment]
Oh, thought this was a 74X. You almost have the 74X version ready?

**Comment by nwoods** [comment]
Hopefully later today. I need to finish some RCT documentation first.

**Pull request merged**
