### PR TITLE
Mini aod 8 0 20

### PR DESCRIPTION
**Pull request by truggles**
Make lhe event weights default to zero when running over data.
in parameters/ztt.py set default for lheweights "off"

### CODE REVIEW

**Comment by truggles** [comment]
Cécile, can you test the "Temporary solution for the LUMI MASK problem" fix to see if there are conflicts that I don't see using my own /afs directory?

If it works, I will find a better way to keep it in there.  Providing all jsons would not be fun.

**Comment by dntaylor** [comment]
@truggles What is the lumi mask problem?

**Comment by dntaylor** [comment]
So you did the push then disappeared. I'm going to assume the "problem" is transient issues reading the json from CERN afs.

What you have done is the wrong way to fix it. Don't use truggles afs.

Instead, copy the json you want into a data directory in one of the packages. This is how it used to be done back in the day when we used datadefs.

https://github.com/uwcms/FinalStateAnalysis/tree/53X_SLC6_Dev/RecoTools/data/masks

**Comment by truggles** [comment]
Thanks Devin.  I undid the lumi_mask work.  It should be good now.

**Pull request merged**
