### PR TITLE
Add electron MVA ID

### PR DESCRIPTION
**Pull request by dntaylor**
Just the working points, still debugging the MVA discriminator.

### CODE REVIEW

**Comment by dntaylor** [comment]
Note: wait until I send the new commit to merge.

**Comment by dntaylor** [comment]
Okay, now its good. Let jenkins run then merge.

**Comment by dntaylor** [comment]
test this please

**Comment by dntaylor** [comment]
I reran Jenkins manually, and it built. Don't know why it didn't update.
@nwoods Good to merge?

**Comment by nwoods** [comment]
[This line](https://github.com/dntaylor/FinalStateAnalysis/blob/miniAOD_dev_74X/NtupleTools/python/embedElectronIDs.py#L49) crashes in 50 ns mode. The fix is to replace

``` python
    mvaValueLabels = ["BDTIDNonTrig"]
    if use25ns:
        mvaValues = [
            cms.InputTag("electronMVAValueMapProducer:ElectronMVAEstimatorRun2Phys14NonTrigValues"),
            ]
```

(ll 36-40) with something like 

``` python
    if use25ns:
        mvaValueLabels = ["BDTIDNonTrig"]
        mvaValues = [
            cms.InputTag("electronMVAValueMapProducer:ElectronMVAEstimatorRun2Phys14NonTrigValues"),
            ]
    else:
        mvaValueLabels = []
        mvaValues = []
```

Please cherry-pick [this commit](https://github.com/nwoods/FinalStateAnalysis/commit/bda217a1da3083db41fb631918821a362f72e1dd) from my area rather than doing it yourself, so we don't screw ourselves up when I PR my stuff.

**Comment by dntaylor** [comment]
Just merge and then we merge yours. Im not going to be at a computer for a while.

**Comment by lgray** [comment]
Hi Guys -- you also store the output MVA category right?
You will need this to apply cuts or WPs consistently later...

-Lindsey

**Comment by dntaylor** [comment]
Thanks @lgray, added.

**Comment by dntaylor** [comment]
Sorry, need to move on. Also, going to switch to 747 for my next PR.

**Pull request merged**
