### PR TITLE
updated to new effective areas

### PR DESCRIPTION
**Pull request by dntaylor**
Hardcoded the Spring15 effective areas for electrons.
Match this: RecoEgamma/ElectronIdentification/data/Spring15/effAreaElectrons_cone03_pfNeuHadronsAndPhotons_25ns.txt

### CODE REVIEW

**Comment by lgray** [comment]
@dntaylor Hardcoding things is bad. 

You may want to use this: https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/RecoEgamma/EgammaTools/interface/EffectiveAreas.h

**Comment by dntaylor** [comment]
Hey Lindsey, thanks. I was hoping for something like that but chose expedience over correctness. Thanks for pointing me to the reference.

**Comment by dntaylor** [comment]
test this please

**Comment by truggles** [comment]
just sent some test jobs running

**Pull request merged**
