### PR TITLE
Jet info, muon ghost cleaning, several new branches needed for HZZ4l analysis

### PR DESCRIPTION
**Pull request by nwoods**
Kind of random assortment of changes here, mostly new branches. The most significant are the addition of default muon ghost cleaning and an option to put basic info about the N highest-pt jets into the ntuple for non-jet final states. Right now just does pt, eta, phi, and PU MVA, but could easily do more. 

@kdlong, this might be relevant to your interests.

### CODE REVIEW

**Comment by nwoods** [comment]
(Extra commit to update README with the jets option)

**Comment by kdlong** [comment]
I am definitely interested. When I was thinking about this I was wondering about adopting a syntax along the line of "mme+4j" to request extra jets and changing the definition of j, which is only b-jets now, to b. So something like "mmj" would not be a valid final state, and "mmb+4j" would give you final states of 2 muons, 1 b jet, and the 4 highest pt jets in addition. Maybe we don't want to muck with the way this syntax works but it seems like it fits more naturally in the final state itself than as a command line argument to me.

I'll look closer over what you did and we can discuss it.

**Comment by nwoods** [comment]
Right now putting `j` in the channel does give you a general jet like you want, it's just called a b-jet in documentation for historical reasons (and because it includes the B-tag variables whether it's b-tagged or not), AFAIK. And I think the channel should be reserved for your analysis channel/final state, ie. the objects that your initial state (Higgs or whatever) decayed into. Certainly, if the jets are not included in the combinatorics, they shouldn't be included in the channel. For this reason, I also put them into the ntuples as `jet1`, `jet2` ... instead of `j1`, `j2` ...

Ultimately, though, this is a semantic issue. It's more important to get the variables you want placed in to the ntuples. There's no reason we couldn't have dijet variables (delta eta and so forth) in here to facilitate VBF/VBS analyses, though this would make the ntuples pretty big for more than a few jets.

**Comment by mcepeda** [comment]
As a note: they are not really called bjets? they are jets...  they were implemented for WBB ;).  I added the previously non existent bjet.py template. If there is more info needed you can just add another template, but do not delete the bjet one please! Lets take the SMP V+bb final states into account! 

Note that if you ask for mjj, for instance, you get trees with a muon and 2 jets, out of which you can ask for btagging. The btagging is not asked for at preselection, it is just added to the tree through that template.

Devin already used this for his B2G analysis with a 4l2J final state as well...

**Comment by mcepeda** [comment]
But I think what you want is something different: the angle between the two jets will automatically be added by FSA if you do it like this, but you are going to get something very complicated for the analysis?

That is they key in the implementation by Evan of the VBF variables: you can run the standard analysis identical for, say, ZZ and for ZZ VBF without having to run two sets of ntuples, one with llll and other with lllljj, which will get cumbersome, imho.

**Comment by kdlong** [comment]
Thanks for the clarification.

**Pull request merged**
