### PR TITLE
Port HZZ changes from 72X to 74X

### PR DESCRIPTION
**Pull request by nwoods**
Looks like we let the branches diverge too much and automatic merger isn't possible. I'm posting it now so others have access to the changes; I'll start looking into the problem with the merge.

### CODE REVIEW

**Comment by nwoods** [comment]
Conflict fixed, can be auto-merged once checked.

**Comment by dntaylor** [comment]
Jenkins fails because of 746p6 v 747. I've switched Jenkins to 747. I'll test manually in 746p6. Then from now on we use 747.

**Comment by nwoods** [comment]
test this please

**Comment by nwoods** [comment]
@dntaylor, did you switch Jenkins over to 747 yet? This failed again, and it looks like the same problem.

**Comment by nwoods** [comment]
Per Devin's request, I'm changing this to include the commits he had as #421, as I already have them merged and one of them will unbreak Jenkins. Also adding a few little tweaks to other stuff.

**Comment by nwoods** [comment]
If somebody who's better at Git than I am knows how to maintain the commit history correctly so all those many changes are represented by more than just one merge commit, please let me know...

**Comment by nwoods** [comment]
Looks like Jenkins is OK with this now; @dntaylor, can you take a look and make sure it's really ready? I only checked my stuff.

**Pull request merged**
