### PR TITLE
First commit with CMSSW_7_5_X

### PR DESCRIPTION
**Pull request by nwoods**
Ntuple maker works but I haven't tested it thoroughly. Main changes were to move all instances of `getByLabel()` to `getByToken()` with a corresponding `consumes<>()`, because the framework now yells at you if you don't have a `consumes<>()` call. Reverted to PHYS14 EGamma IDs because these are the only ones I know for sure work in 75X. I know of another set that will probably work, but I wanted to get this PR squared away before I move to them. 

While I was at it, I updated all the modules I touched to work multithreaded. There are a few left to update, but it's a pretty easy change. Two modules, `PATFinalStateAnalysisFilter` and `MiniAODHZZMEEmbedder` are `one` modules that will slow things down enormously when multithreaded. For `MinAODHZZMEEmbedder` there's not much of a way around this, but some enterprising person could refactor `PATFinalStateAnalysisFilter` to work as a `stream` module.

### CODE REVIEW

**Comment by nwoods** [comment]
@dntaylor, could you set Jenkins up to monitor this branch and do the relevant tests in the right CMSSW version? I made these edits in 752.

**Comment by dntaylor** [comment]
@nwoods It's setup. I'm building the base branch now.

**Comment by dntaylor** [comment]
Build fine. Something killed jenkins and I had to restart.

**Comment by nwoods** [comment]
Test this please.

**Comment by nwoods** [comment]
test this please

**Comment by lgray** [comment]
@nwoods. All the up-to-date EGM IDs will come with 753.

**Comment by nwoods** [comment]
@lgray Awesome, thanks for the heads up. Actually, I've been meaning to ask, is there an electron ID or pair of IDs that will allow direct working-point independent comparisons of 74X and 75X? The point of all this is to validate 75 before the upcoming re-reco at analysis level, but I'm not sure how to do that for electrons right now.

@dntaylor Is something up with Jenkins? I'm not sure why it hasn't tested the most recent commits.

**Comment by lgray** [comment]
@nwoods The best way to validate that right now would be to work from a 75X integration build (`cmsrel CMSSW_7_5_X_2015-09-15-2300` for instance). The ID code and workflows are identical. Obviously re-reco can cause migrations.

**Comment by lgray** [comment]
More info:

If you start with the IB I mentioned above, you should add the following PRs to both 74X and 75X:
https://github.com/cms-sw/cmssw/pull/11231
and 
https://github.com/cms-sw/cmssw/pull/11261

**Comment by dntaylor** [comment]
jenkins got full

**Comment by dntaylor** [comment]
@nwoods 753 is out, want me to switch jenkins to build in that?

**Comment by nwoods** [comment]
I just saw that but I haven't looked closely at the changes yet. Let me try it and see what needs to change first. I'm using it with an integration build for the time being anyway.

**Comment by dntaylor** [comment]
@nwoods I assume 75X has fallen by the wayside until after December jamboree? Can we just close this and start again later making the 75X branch match the 74X branch? It'll be easier to keep things up to date later.

**Comment by lgray** [comment]
75X will be for heavy ion data only. Next pp data (moriond rereco) will be
76X anyway.

(Sent from my Nexus 6)

**Comment by nwoods** [comment]
It's fine to close this for now, but the changes will be needed for 76X too, and they were a lot of (really boring) work so let's resurrect this at some point. If I have time soon (haha) I'll try to rebase this onto the changes we've made to 74X since. So it's not quite so big a pain when we start thinking about 76X.

**Pull request closed without merging**
