### PR TITLE
Mini aod 9 4 0x

### PR DESCRIPTION
**Pull request by truggles**
* Updating 2017 GTs
* Adding bad MET filter not in miniAOD
* Skipping JEC for data.
   * Are people using non-31March2018 rereco?  If so, this commit needs to be altered.

### CODE REVIEW

**Review by psiddire — COMMENTED** [review]
It should also include options.isEmbed, right. Because we are applying JEC from data to Embedded samples

**Comment by truggles** [comment]
The latest embedded samples are using the rereco data from 31March2018, aren't they?  If they are, then I would think we skip JEC for them just like we skip it for data based on the most current recommendations.

**Comment by psiddire** [comment]
I couldn't find the parent for embedded samples on das, so I am not sure if they are produced from Mar 31st. Now that I think of it, the data's global tag takes care of it. So, this should be fine.

**Comment by cecilecaillol** [comment]
The embedded samples are based on 17Nov2017

**Pull request merged**
